### ISSUE TITLE
react-native run-android报错

### ISSUE THREAD

**Issue by chenpengjun** [cyqresig/ReactNativeComponentDemos#3]
* Where:
Build file '/Users/***/work/github/ReactNativeComponentDemos/android/app/build.gradle' line: 116

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find property 'CYQ_RELEASE_STORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

**Comment by cyqresig** [comment]
您好，这个错误信息应是指您使用了release模式但没有配置CYQ_RELEASE_STORE_FILE这个签名文件，如果您只是作调试的话，您可以将这个文件里的signingConfigs release相关部分的内容删除。

**Comment by wploey** [comment]
react-native run-android新错误
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.reactnativecomponent.splashscreen'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

**Comment by cyqresig** [comment]
您好，应该是您引用的另一个插件，包名重了。。。

**Comment by prsu-db** [comment]
1. will this support for scroll view?
2. will this support for scroll view which is inside having a list view?

**Comment by prsu-db** [comment]
1. will this support for scroll view
2. will this support for scroll view which is having embedded list view

**Comment by mataoct** [comment]
@cyqresig  我也遇到了 @wploey 一样的问题，经检查发现 在 setting.gradle里面，存在两个组件react-native-smart-splashscreen 与 react-native-smart-splash-screen ，但是，我们并没有react-native-smart-splashscreen 存在，分别在setting.gradle 和 app.gradle 删掉对应引用就行了,改一下呗
